# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hotelbay
spring.datasource.username=hotelbay
spring.datasource.password=hotelbay123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect